# Generated by Django 4.2.7 on 2023-11-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('grid', 'Grid')], max_length=10)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='smartreport_app.reporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='KpiReportElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=128)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartreport_app.kpi')),
                ('report_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='smartreport_app.reporttemplatepage')),
            ],
        ),
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('scatter', 'Scatter'), ('pie', 'Pie')], max_length=128)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_charts', to='smartreport_app.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('parent', 'Parent'), ('project_manager', 'Project Manager'), ('machine_maintainer', 'Machine Maintainer')], max_length=20)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartreport_app.kpi')),
            ],
        ),
    ]
