# Generated by Django 4.2.7 on 2023-11-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('grid', 'Grid')], max_length=10)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='smartreport_app.reporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='KpiReportElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie'), ('scatter', 'Scatter')], max_length=10, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartreport_app.kpi')),
                ('report_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='smartreport_app.reporttemplatepage')),
            ],
        ),
    ]
