# Generated by Django 4.2.7 on 2023-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityDoctor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityMachineMaintainer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityParent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityProjectManager',
            field=models.IntegerField(default=0),
        ),
    ]
