# Generated by Django 4.2.7 on 2023-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='allowed_charts',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ChartType',
        ),
    ]
