# Generated by Django 4.2.7 on 2023-11-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlayout',
            name='layout',
            field=models.JSONField(),
        ),
    ]
