# Generated by Django 4.2.7 on 2023-11-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('parent', 'Parent'), ('project_manager', 'Project_manager'), ('machine_mantainer', 'Machine_mantainer')], max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartreport_app.kpi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='smartreport_app.user')),
            ],
        ),
    ]
