# Generated by Django 4.2.7 on 2023-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0002_user_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='priorityForDoctor',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityForMachine_mantainer',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityForParent',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priorityForProject_manager',
            field=models.IntegerField(default=9999),
        ),
    ]
