# Generated by Django 4.2.7 on 2023-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0002_kpi_allowed_charts_delete_charttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='allowed_charts',
            field=models.JSONField(default=['line', 'bar', 'pie', 'doughnut', 'radar']),
        ),
    ]
