# Generated by Django 4.2.7 on 2023-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0003_kpi_priorityfordoctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
    ]
