# Generated by Django 4.2.7 on 2023-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0003_dashboardlayout_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedreport',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('parent', 'Parent'), ('project_manager', 'Project Manager'), ('machine_maintainer', 'Machine Maintainer')], default='doctor', max_length=128),
            preserve_default=False,
        ),
    ]
