# Generated by Django 4.2.7 on 2023-11-23 15:31

from django.db import migrations, models
import django.db.models.deletion
import smartreport_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0004_archivedreport_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='name',
            new_name='kb_id',
        ),
        migrations.RemoveField(
            model_name='kpireportelement',
            name='kpi',
        ),
        migrations.AddField(
            model_name='kpi',
            name='kb_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kb_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kb_formula',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kb_name',
            field=models.CharField(default='default_value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='kb_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kb_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='user_type',
            field=models.JSONField(default=smartreport_app.models.DEFAULT_USER_CHOICES),
        ),
        migrations.CreateModel(
            name='KpiReportElementKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears_in', to='smartreport_app.kpi')),
                ('kpiReportElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='smartreport_app.kpireportelement')),
            ],
        ),
    ]
