# Generated by Django 4.2.7 on 2023-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0005_rename_name_kpi_kb_id_remove_kpireportelement_kpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('parent', 'Parent'), ('project_manager', 'Project Manager'), ('machine_maintainer', 'Machine Maintainer')], max_length=128)),
                ('emails', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='archivedreport',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
