# Generated by Django 4.2.7 on 2023-11-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0005_kpi_barplot_kpi_doughnutplot_kpi_lineplot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('parent', 'Parent'), ('project_manager', 'Project_manager'), ('machine_mantainer', 'Machine_mantainer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='kpi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartreport_app.kpi'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='smartreport_app.user'),
        ),
    ]
