# Generated by Django 4.2.7 on 2023-11-24 09:12

from django.db import migrations, models
import smartreport_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0006_email_archivedreport_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='allowed_charts',
            field=models.JSONField(blank=True, default=smartreport_app.models.DEFAULT_CHART_CHOICES, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='user_type',
            field=models.JSONField(blank=True, default=smartreport_app.models.DEFAULT_USER_CHOICES, null=True),
        ),
    ]
