# Generated by Django 4.2.7 on 2023-11-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0004_reporttemplateimage'),
        ('smartreport_app', '0007_alter_kpi_allowed_charts_alter_kpi_user_type'),
    ]

    operations = [
    ]
