# Generated by Django 4.2.7 on 2023-11-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0010_remove_kpi_isnew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='created',
            new_name='kb_created',
        ),
    ]
