# Generated by Django 4.2.7 on 2023-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0012_rename_kb_created_kpi_kb_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpireportelement',
            name='kpis',
            field=models.ManyToManyField(related_name='appears_in', to='smartreport_app.kpi'),
        ),
        migrations.DeleteModel(
            name='KpiReportElementKpi',
        ),
    ]
