# Generated by Django 4.2.7 on 2023-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0012_rename_kb_created_kpi_kb_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
