# Generated by Django 4.2.7 on 2023-11-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0013_kpireportelement_kpis_delete_kpireportelementkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='priority_doctor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priority_machine_maintainer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priority_parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='priority_project_manager',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='archivedreport',
            name='file',
            field=models.FileField(upload_to='tmp/reports/'),
        ),
        migrations.AlterField(
            model_name='kpireportelement',
            name='kpis',
            field=models.ManyToManyField(to='smartreport_app.kpi'),
        ),
    ]
