# Generated by Django 4.2.7 on 2023-11-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0013_kpireportelement_kpis_delete_kpireportelementkpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedreport',
            name='template',
        ),
        migrations.AlterField(
            model_name='archivedreport',
            name='created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_reports', to='smartreport_app.reporttemplate'),
        ),
        migrations.AlterField(
            model_name='kpireportelement',
            name='kpis',
            field=models.ManyToManyField(to='smartreport_app.kpi'),
        ),
    ]
