# Generated by Django 4.2.7 on 2023-11-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0013_kpireportelement_kpis_delete_kpireportelementkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='smart',
            field=models.BooleanField(auto_created=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='kpireportelement',
            name='kpis',
            field=models.ManyToManyField(to='smartreport_app.kpi'),
        ),
    ]
