# Generated by Django 4.2.7 on 2023-11-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0014_reporttemplate_smart_alter_kpireportelement_kpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartReportTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Smart Report Template',
                'verbose_name_plural': 'Smart Report Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('smartreport_app.reporttemplate',),
        ),
    ]
