# Generated by Django 4.2.7 on 2023-11-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartreport_app', '0014_remove_archivedreport_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedreport',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archived_reports', to='smartreport_app.reporttemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
